image: node:alpine

stages:
  - test
  - build
  - dockerrize

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

variables:
  CFG_MONGO_HOST: "mongo"

test:
  stage: test
  services:
    - name: mongo
      alias: mongo
  script:
    - apk --update add git
    - npm install
    - npm run test

build:
  stage: build
  script:
    - apk --update add git
    - npm install
    - npm run build
  artifacts:
    paths:
    - ./server/course/dist
    - ./server/watch/dist
    - ./server/web/dist
    expire_in: 5 minutes

dockerrize:
  image: tmaier/docker-compose:latest
  stage: dockerrize
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker-compose build
    - docker-compose push
  dependencies:
    - build
  only:
    - master

