image: node:alpine

stages:
  - build
  - deploy

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

variables:
  CFG_MONGO_HOST: "mongo"

test:
  stage: build
  services:
    - name: mongo
      alias: mongo
  script:
    - apk --update add git
    - npm install
    - npm test
