version: '2'

services:

  web:
    image: rainu/cryptotrack-web
    build:
      context: ./server/web/
    environment:
      - CFG_MONGO_HOST=db
    ports:
      - "3000:3000"
    depends_on:
      - db

  watch:
    image: rainu/cryptotrack-watch
    build:
      context: ./server/watch/
    environment:
      - CFG_MONGO_HOST=db
    depends_on:
      - db

  course:
    image: rainu/cryptotrack-course
    build:
      context: ./server/course/
    environment:
      - CFG_MONGO_HOST=db
    depends_on:
      - db

  db:
    image: mongo
    restart: always